define([], function() {
  return {
    "PropertyPaneAbout": "About",
    "PropertyPaneDescription": "Description",
    "PropertyPaneMainDescription": "Main Settings",
    "PropertyPaneColumnsDescription": "Column Settings",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "description": "Description",
    "listDefinition": "List Type",
    "listWebURL": "URL of site with Tabbed Tiles List",
    "listTitle": "Tabbed Tiles list",
    "defaultTab": "Default Tab",
    "colTitleText": "Tile Text",
    "colHoverText": "Tile Hover Text",
    "colCategory": "Tile Tab/Category",
    "colColor": "Background Color",
    "colSize": "Tile Size",
    "colGoToLink": "Destination Link",
    "colOpenBehaviour": "Open behaviour",
    "colImageLink": "Image Link",
    "colSort": "Sort Order",
    "colTileStyle": "Custom Style Options (JSON)",
  }
});